export const initialState = {
  user: {
    id: "",
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    phone: "",
    image: "",
    roleId: "",
    isActive: null,
  },
  userLoader: false,
  userError: null,
  reload: false,
  metrics: [
    { title: "Compromisos existentes en la plataforma", total: "240" },
    { title: "Compromisos logrados en la plataforma", total: "80" },
    { title: "Compromisos activos en la plataforma", total: "160" },
    { title: "Agentes activos en la plataforma", total: "1500" },
    { title: "Compromisos asignados", total: "15" },
    { title: "Compromisos asignados finalizados", total: "10" },
    { title: "Compromisos asignados activos", total: "5" },
  ],
  commitmentsCurrentsPool: [],
  commitmentsCurrentsPoolLoader: false,
  commitmentsCurrentsPoolError: null,
  commitmentsCurrentsTracing: [],
  commitmentsCurrentsTracingLoader: false,
  commitmentsCurrentsTracingError: null,
  commitmentsCurrentsManagement: [],
  commitmentsCurrentsManagementLoader: false,
  commitmentsCurrentsManagementError: null,
};
