export const actions = {
  getCommitment: "GET_COMMITMENT",
  getCommitmentSuccess: "GET_COMMITMENT_SUCCESS",
  getCommitmentError: "GET_COMMITMENT_ERROR",

  getCollaboratorsList: "GET_COLABORATORS",
  getCollaboratorsListSuccess: "GET_COLABORATORS_SUCCESS",
  getCollaboratorsListError: "GET_COLABORATORS_ERROR",
  setColaborator: "SET_COLABORATOR",
  saveColaborators: "SAVE_COLABORATOR",
  errorColaborators: "ERROR_COLABORATOR",
  setReload: "SET_RELOAD",
  updateStatusCommitment: "UPDATE_STATUS_COMMITMENT",
  updateStatusCommitmentSuccess: "UPDATE_STATUS_COMMITMENT_SUCCESS",
  updateStatusCommitmentError: "UPDATE_STATUS_COMMITMENT_ERROR",
  dropDownStatusOpen: "DROPDOWN_STATUS_OPEN",
  dropDownStatusClose: "DROPDOWN_STATUS_CLOSE",
  setCommitmentStatus: "SET_COMMITMENT_STATUS",
  wrapperAddCollaboratorOnOff: "WRAPPER_ADD_COLLABORATOR_On_Off",
  deletedCollaborator: "DELETED_COLLABORATOR",
  deletedCollaboratorSuccess: "DELETED_COLLABORATOR_SUCCESS",
  deletedCollaboratorError: "DELETED_COLLABORATOR_ERROR",

  updateFieldAddTask: "UPDATE_FIELD_ADD_TASK",
  addTask: "ADD_TASK",
  addTaskSuccess: "ADD_TASK_SUCCESS",
  addTaskError: "ADD_TASK_ERROR",
  getTasksList: "GET_TASKS_LIST",
  getTasksListSuccess: "GET_TASKS_LIST_SUCCESS",
  getTasksListError: "GET_TASKS_LIST_ERROR",
  updateTask: "UPDATE_TASK_",
  updateTaskSuccess: "UPDATE_TASK_SUCCESS",
  updateTaskError: "UPDATE_TASK_ERROR",
  removeTask: "REMOVE_TASK",
  removeTaskSuccess: "REMOVE_TASK_SUCCESS",
  removeTaskError: "REMOVE_TASK_ERROR",
  showModalAddTask: "SHOW_MODAL_ADD_TASK",
  showModalEditTask: "SHOW_MODAL_EDIT_TASK",
  closeModalEditTask: "CLOSE_MODAL_EDIT_TASK",

  getMilestones: "GET_MILESTONES",
  getMilestonesSuccess: "GET_MILESTONES_SUCCESS",
  getMilestonesError: "GET_MILESTONES_ERROR",
  addMilestone: "ADD_MILESTONE",
  addMilestoneSuccess: "ADD_MILESTONE_SUCCESS",
  addMilestoneError: "ADD_MILESTONE_ERROR",
  updateFieldMilestone: "UPDATE_FIELD_MILESTONE",
  updateMilestone: "UPDATE_MILESTONE",
  updateMilestoneSuccess: "UPDATE_MILESTONE_SUCCESS",
  updateMilestoneError: "UPDATE_MILESTONE_ERROR",
  showModalAddMilestone: "SHOW_MODAL_ADD_MILESTONE",
  showModalEditMilestone: "SHOW_MODAL_EDIT_MILESTONE",
  closeModalEditMilestone: "CLOSE_MODAL_EDIT_MILESTONE",
};
