export const initialState = {
  commitment: { collaborators: [] },
  commitmentLoading: false,
  commitmentError: null,
  updateStatus: false,
  errorUpdateStatus: null,
  listColaborators: [],
  loadingColaborators: false,
  errorColaborators: null,
  likelyCollaborator: [],
  loadinglikelyCollaborator: false,
  errorlikelyCollaborator: null,
  reload: false,
  dropdownStatus: null,
  wrapperAddCollaborator: false,
  loadingDeletedCollaborator: false,
  errorDeletedCollaborator: null,
  tasks: [],
  tasksLoading: false,
  tasksError: null,
  reloadTasks: false,
  newTask: {
    title: "",
    description: "",
    date: "",
  },
  newTaskLoading: false,
  newTaskError: null,
  showModalTask: false,
  isEditModalTask: false,
  msgError: null,

  milestones: [],
  milestonesLoading: false,
  milestonesError: null,
  reloadMilestones: false,
  milestone: {
    title: "",
    description: "",
    date: "",
  },
  showModalMilestone: false,
  isEditModalMilestone: false,

  page: 1,
  pageLimit: 1,
};
