export const initialState = {
  commitment: { collaborators: [] },
  commitmentLoading: false,
  commitmentError: null,
  updateStatus: false,
  errorUpdateStatus: null,
  listColaborators: [],
  loadingColaborators: false,
  errorColaborators: null,
  likelyCollaborator: [],
  loadinglikelyCollaborator: false,
  errorlikelyCollaborator: null,
  reload: false,
  dropdownStatus: null,
  wrapperAddCollaborator: false,
  loadingDeletedCollaborator: false,
  errorDeletedCollaborator: null,
  tasks: [],
  tasksLoading: false,
  tasksError: null,
  reloadTasks: false,
  newTask: {
    title: "",
    description: "",
    date: "",
  },
  newTaskLoading: false,
  newTaskError: null,
  showModalTask: false,
  isEditModalTask: false,
  msgError: null,
  milestones: [
    {
      id: 1,
      commitmentId: 1,
      title: "Se abrieron 100 lugares para escalar mipymes",
      date: "24/sep/2020",
      description:
        "La empresa junto a los agentes de cambio proveidos por ashoka lograron conseguir una finaciación para ayudar a 100 empresas a escalar.",
      organization: "empresas22",
    },
    {
      id: 2,
      commitmentId: 1,
      title: "Se consigui la 2da ronda de inversión",
      date: "10/sep/2020",
      description:
        "La empresa junto a los agentes de cambio proveidos por ashoka lograron conseguir una finaciación para ayudar a 100 empresas a escalar.",
      organization: "empresas22",
    },
  ],
  milestonesLoading: false,
  milestonesError: null,
  reloadMilestones: false,
  milestone: {
    title: "",
    description: "",
    date: "",
  },
  showModalMilestone: false,
  isEditModalMilestone: false,
};
