export const actions = {
  getUsers: "GET_USERS",
  getUsersSuccess: "GET_USERS_SUCCESS",
  getUsersError: "GET_USERS_ERROR",
  showModalAddUser: "SHOW_MODAL_ADD_USER",
  showModalEditUser: "SHOW_MODAL_EDIT_USER",
  closeModalEditUser: "CLOSE_MODAL_EDIT_USER",
  updateUser: "UPDATE_USER",
  addUser: "ADD_USER",
  addUserSuccess: "ADD_USER_SUCCESS",
  addUserError: "ADD_USER_ERROR",
  saveUpdateUser: "SAVE_UPDATE_USER",
  saveUpdateUserSuccess: "SAVE_UPDATE_USER_SUCCESS",
  saveUpdateUserError: "SAVE_UPDATE_USER_ERROR",
  removeUser: "REMOVE_USER",
  removeUserSuccess: "REMOVE_USER_SUCCESS",
  removeUserError: "REMOVE_USER_ERROR",
  addUserSuccess: "ADD_USER_SUCCESS",
  addUserError: "ADD_USER_ERROR",
  setPage: "SET_PAGE",
};
