export const initialState = {
  users: [],
  usersLoader: false,
  msgError: null,
  reload: false,
  showModal: false,
  isEditModal: false,
  user: {
    id: "",
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    phone: "",
    image: "",
    roleId: "",
    isActive: null,
  },
  addUserLoader: false,
  page: 1,
  pageLimit: 1,
  //User Filtro
  searchFilter: {
    agent: "",
    collaborator: "",
    userManagement: "",
    user: "",
    area: "",
    state: "",
    sector: "",
    status: "",
    rol: null,
    isActive: null,
  },
};
