export const actions = {
  getCommitment: "GET_COMMITMENT",
  getCommitmentSuccess: "GET_COMMITMENT_SUCCESS",
  getCommitmentError: "GET_COMMITMENT_ERROR",
  getCollaboratorsList: "GET_COLABORATORS",
  getCollaboratorsListSuccess: "GET_COLABORATORS_SUCCESS",
  getCollaboratorsListError: "GET_COLABORATORS_ERROR",
  setColaborator: "SET_COLABORATOR",
  saveColaborators: "SAVE_COLABORATOR",
  errorColaborators: "ERROR_COLABORATOR",
  setReload: "SET_RELOAD",
  updateStatusCommitment: "UPDATE_STATUS_COMMITMENT",
  updateStatusCommitmentSuccess: "UPDATE_STATUS_COMMITMENT_SUCCESS",
  updateStatusCommitmentError: "UPDATE_STATUS_COMMITMENT_ERROR",
  dropDownStatusOpen: "DROPDOWN_STATUS_OPEN",
  dropDownStatusClose: "DROPDOWN_STATUS_CLOSE",
  setCommitmentStatus: "SET_COMMITMENT_STATUS",
  wrapperAddCollaboratorOnOff: "WRAPPER_ADD_COLLABORATOR_On_Off",
};
