export const actions = {
  getCommitments: "GET_COMMITMENTS",
  getCommitmentsSuccess: "GET_COMMITMENTS_SUCCESS",
  getCommitmentsError: "GET_COMMITMENTS_ERROR",
  filterCommitments: "FILTER_COMMITMENTS",
  exportData: "EXPORT_DATA",
  exportDataSuccess: "EXPORT_DATA_SUCCESS",
  exportDataError: "EXPORT_DATA_ERROR",
  sync: "SYNC",
  syncSucess: "SYNC_SUCCESS",
  syncError: "SYNC_ERROR",
  setSearchFilter: "GET_SEARCH_FILTER",
  getCommitmentsTracing: "GET_COMMITMENTS_TRACING",
  getCommitmentsSuccessTracing: "GET_COMMITMENTS_SUCCESS_TRACING",
};